# 실제 운영용이 아니기 때문에 env 미사용

spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    hikari:
      maximum-pool-size: 4
    url: jdbc:postgresql://localhost:5432/my_database
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      url: redis://localhost:6379

jwt:
  secret-key: aB3xK7mN9qR5sT8uV2wY4zA6cE1fH0jL
  token:
    expired-time-ms: 2592000000 # 30days